### ISSUE TITLE
RFE: View Mode tap to expand/collapse header

### ISSUE THREAD

**Issue by dotancohen** [metanote-dev/metanote-dev.github.io#3]
When in View Mode (Accessed through the Buffer Info icon, then select Major mode), it would be helpful if headings could be expanded or collapsed on tap.

I'm using Metanote 0.4.1.1(742) which is the latest version on Google Play, installed just a few minutes ago. This is on a Boox Note Air 2 Plus (E-Ink Android tablet).

**Comment by metanote-dev** [comment]
It already supports but by using double-click on headline. One tap enter editing mode and double tap expand or collapse entry.
