### ISSUE TITLE
ID or file link support

### ISSUE THREAD

**Issue by gatlee** [metanote-dev/metanote-dev.github.io#7]
Love the app. Just curious if there are any plans to support ID links in the future. Would go really well with my org-roam setup

**Comment by metanote-dev** [comment]
Thank you. ID links, file links, headline links and supporting for org-roam are already on my list, recently,I'm working on supporting for table, src block, and org visibility cycle ;)

**Comment by metanote-dev** [comment]
Links and attachments are supported starting from iOS 0.16.0.

**Comment by gatlee** [comment]
Hi, I've had a poke around after updating and am struggling to find how to do this. Is there documentation on how to create these file links?

**Comment by gatlee** [comment]
Sorry,

Missed this

https://metanote-dev.github.io/hyperlinks_and_attachments.html
